apiVersion: apps/v1
kind: Deployment
metadata:
  name: sw-heatmap
  namespace: sw-heatmap
  labels:
    app: sw-heatmap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sw-heatmap
  template:
    metadata:
      labels:
        app: sw-heatmap
    spec:
      containers:
      - name: static
        image: ghcr.io/npflan/sw-heatmap-static:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: api
        image: ghcr.io/npflan/sw-heatmap:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: "SW_HEATMAP_PROMETHEUS_URL"
            value: "http://prom.npf"
          - name: "SW_HEATMAP_METRICS_QUERY"
            value: "probe_success"
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: sw-heatmap
  name: sw-heatmap
  namespace: sw-heatmap
spec:
  clusterIP: 10.97.10.11
  ports:
  - name: http-static
    port: 80
    targetPort: 80
  - name: http-api
    port: 8080
    targetPort: 8080
  selector:
    app: sw-heatmap
